USE [master]
GO

/****** Object:  Database [MunicipalityTax]    Script Date: 22-11-2020 20:18:04 ******/
CREATE DATABASE [MunicipalityTax]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MunicipalityTax', FILENAME = N'c:\temp\MunicipalityTax.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MunicipalityTax_log', FILENAME = N'c:\temp\MunicipalityTax.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MunicipalityTax].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MunicipalityTax] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [MunicipalityTax] SET ANSI_NULLS ON 
GO

ALTER DATABASE [MunicipalityTax] SET ANSI_PADDING ON 
GO

ALTER DATABASE [MunicipalityTax] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [MunicipalityTax] SET ARITHABORT ON 
GO

ALTER DATABASE [MunicipalityTax] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MunicipalityTax] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MunicipalityTax] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MunicipalityTax] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MunicipalityTax] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [MunicipalityTax] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [MunicipalityTax] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MunicipalityTax] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [MunicipalityTax] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MunicipalityTax] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MunicipalityTax] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MunicipalityTax] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MunicipalityTax] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MunicipalityTax] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MunicipalityTax] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MunicipalityTax] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MunicipalityTax] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MunicipalityTax] SET RECOVERY FULL 
GO

ALTER DATABASE [MunicipalityTax] SET  MULTI_USER 
GO

ALTER DATABASE [MunicipalityTax] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MunicipalityTax] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MunicipalityTax] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MunicipalityTax] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MunicipalityTax] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MunicipalityTax] SET QUERY_STORE = OFF
GO

USE [MunicipalityTax]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [MunicipalityTax] SET  READ_WRITE 
GO
USE [MunicipalityTax]

CREATE TABLE [dbo].[MunicipalityTaxSchedule] (
    [Municipality]    VARCHAR (100)  NOT NULL,
    [TaxScheduleType] INT            NOT NULL,
    [ValidFrom]       DATETIME       NOT NULL,
    [ValidTo]         DATETIME       NOT NULL,
    [Tax]             DECIMAL (9, 4) NOT NULL,
    CONSTRAINT [PK_MunicipalityTaxSchedule] PRIMARY KEY CLUSTERED ([Municipality] ASC, [TaxScheduleType] ASC, [ValidFrom] ASC)
);